"""Build a central evidence page using recorded artifacts, with explicit GIF paths."""
from pathlib import Path
import html
import os
import json
ROOT=Path(__file__).resolve().parents[1];out=ROOT/'docs/vla-research.html'
def link(path,label):
    return f'<a href="{os.path.relpath(ROOT/path,out.parent)}">{html.escape(label)}</a>'
def media(path,label):
    if not (ROOT/path).exists():return f'<p>Artifact unavailable: {html.escape(path)}</p>'
    return f'<figure><figcaption>{html.escape(label)}</figcaption><img loading="lazy" src="{os.path.relpath(ROOT/path,out.parent)}"><div class="path">{html.escape(path)}</div></figure>'
body='''<h1>From visual binding to Minecraft navigation</h1><p class="lead">What visual information is available, what the policy uses, and whether it reaches the requested object.</p><nav><a href="#history">Experiments</a> · <a href="#results">Results</a> · <a href="#gallery">GIF evidence</a> · <a href="#maps">Reading the maps</a> · <a href="#next">Next experiment</a></nav>
<h2 id="history">What we have done</h2><ol><li><b>Frozen-model interventions:</b> first patched final-token Q in the language decoder, then vision residual states and Q/K/V activations. V30 means the value projection at zero-based vision block 30. These were inference interventions, not policy training.</li><li><b>Destination choice and scripted replay:</b> tested selected destinations and executed movement with a controller. Scripted replay is different from a learned policy repeatedly interpreting new frames.</li><li><b>Teacher demonstrations:</b> collected 384 successful privileged-controller episodes. Teacher success is not learner success.</li><li><b>Learned closed-loop policy:</b> frozen visual features → 4×8 pooling → instruction-conditioned attention → recurrent memory → forward, left, right, stop. The small policy was trained; Qwen was frozen.</li><li><b>Navigation ablations:</b> varied visual preprocessing, loss weighting, and training seed. Reliable navigation was not achieved.</li><li><b>Privileged perception:</b> known object boxes plus small color/shape readouts. Finer grids succeeded on the current validation captures.</li></ol>'''
body+=link('research-placeholder','') if False else ''
for path,label in [('runs/oscar/q-color-pilot-01/report.html','Decoder Q-patching report'),('runs/oscar/vision-pilot-01/report.html','Vision intervention report'),('runs/oscar/navigation-study-reliability-v1/analysis/explained.html','Navigation reliability analysis'),('runs/oscar/perception-study-perception-v1/report.html','Perception diagnostic report')]:
 body+='<p>'+link(path,label)+'</p>'
body+='<h2>RL v2 result and seed correction</h2><p>All nine jobs completed, but all 576 validation episodes timed out with zero success. Training had zero successful present-target arrivals. Within each reward condition, action histories matched across all three nominal seeds because Qwen construction reset the global RNG. These are not independent replications. Policy initialization and scene/action sampling now use isolated seed handling; the corrected smoke job 7145617 completed, with 0/2 present-target validation successes after two short training episodes (user-supplied Oscar log). This confirms execution, not learning.</p><p>'+link('runs/oscar/rl-navigation-rl-v2/analysis/explained.html','RL failure analysis, trajectories and movement GIFs')+'</p>'
body+='''<h2 id="results">Measured results</h2><table><tr><th>Navigation seed</th><th>Timestep weighting</th><th>Extra startup/turn weighting</th></tr><tr><td>731</td><td>12/56</td><td>6/56</td></tr><tr><td>732</td><td>6/56</td><td>4/56</td></tr><tr><td>733</td><td>17/56</td><td>10/56</td></tr></table><p>Correct present-target arrivals. Same validation tasks across seeds, not independent scenes. Extra weighting reduced arrivals in every seed. Absence success requires an immediate stop: 1/24 versus 0/24.</p><table><tr><th>Known-region perception</th><th>4×8</th><th>8×16</th><th>Native 20×32</th></tr><tr><td>Color</td><td>56/56</td><td>56/56</td><td>56/56</td></tr><tr><td>Shape</td><td>50/56</td><td>56/56</td><td>56/56</td></tr><tr><td>Present selection</td><td>50/56</td><td>56/56</td><td>56/56</td></tr><tr><td>Absent rejection</td><td>4/8</td><td>8/8</td><td>8/8</td></tr></table><p>64 goals over 16 capture images, four families in one validation geometry group. Known boxes and an explicit factorized selection rule are privileged. This shows decodable attributes, not autonomous detection or a native binding circuit. Test geometry remains untouched.</p>'''
body+=media('runs/oscar/binding-captures-24-6961501/perception-audit/000004.png','Known boxes and 4×8 versus 8×16 grids: coarse cells mix structure and background')
body+='''<h2 id="gallery">Recorded movement and attribution</h2><p>These examples are selected to illustrate contrasting outcomes, not a random sample. No V30/V31 intervention is applied in these learned-policy rollouts. GIF playback follows simulation ticks, not model inference latency.</p>'''
for arm,eid,title,note in [('timestep-s733','e00000','Requested red pillar: correct arrival','The endpoint meets the approach-waypoint criterion.'),('timestep-s733','e00001','Requested blue pillar: wrong object','Recorded frames show approach to the red pillar. A concentrated attention map can accompany an incorrect choice.'),('startup-turn-s733','e00002','Requested red arch: stopped outside tolerance','The agent approaches the requested arch but misses the waypoint criterion. This is not automatically a binding error.'),('startup-turn-s731','e00063','Requested blue arch: unsuccessful','47 decisions; final distance 10.03 blocks. First action has concentrated attention but zero positive Grad-CAM.')]:
 base=f'runs/oscar/navigation-study-reliability-v1/rollout-{arm}';body+=f'<h3>{title}</h3><p>{note}</p><div class="triplet">'
 for path,label in [(f'{base}/episodes/{eid}/movement.gif','Minecraft movement'),(f'{base}/maps/{eid}/policy-attention.gif','Controller cross-attention'),(f'{base}/maps/{eid}/action-gradcam.gif','Chosen-action Grad-CAM')]:body+=media(path,label)
 body+='</div><p>'+link(f'{base}/episodes/{eid}/report.html','Episode trajectory and outcome')+'</p>'
body+='''<h2 id="maps">What the maps and decision JSON mean</h2><p><b>Action probabilities:</b> [forward, turn_left, turn_right, stop]. The largest value determines the action. A 98.7% forward preference is not a 98.7% chance of reaching the target.</p><p><b>Policy attention:</b> the instruction query weights 32 pooled visual regions, averaged across four controller heads. Indices run left-to-right through four rows of eight. This is not Qwen ViT-head attention and not a V30 patch mask.</p><p><b>Action Grad-CAM:</b> positive gradient-weighted attribution at the pooled visual features for the selected action logit, with preceding memory fixed. If the action changes from forward to stop, the score being explained changes. Negative contributions are clipped; an all-zero map does not prove the image was ignored.</p><p>Heatmaps are smoothed and normalized independently per frame. Equal brightness is not equal attribution magnitude. Neither map is a segmentation or causal explanation. Interventions and behavior are needed to test causality.</p>
<h2 id="next">Optional diagnostic: moving-frame perception</h2><p>Freeze the successful 8×16 readout and threshold. Sample all 64 episodes at eight-decision intervals plus unique start/middle/end frames, generate geometry-based proposals, and explicitly audit visible regions, then evaluate attribute and visible-target selection accuracy by phase. No retraining and no new Minecraft collection.</p><p>Starting boxes cannot be reused after the camera turns. Object metadata gives identity, not visibility. This optional audit requires visible boxes or an explicit occluded/out-of-frame/uncertain label. Ambiguous frames are excluded from selection scoring. A target outside the view is not absent from the world.</p><ol><li>If audited live-frame recognition fails: investigate viewpoint/appearance shift.</li><li>If it succeeds: replace privileged boxes with learned localization.</li><li>Once selection generalizes: reconnect it to movement and collect corrective on-policy demonstrations.</li><li>With a reliable clean baseline: revisit V30/V31 and head-level necessity/sufficiency interventions.</li></ol>'''
body+='<h2>Current primary direction: online RL</h2><p>Manual labels are not required. The privileged-region readout remains optional diagnostics. New experiments train an actor-critic from simulator rewards, with an optional self-supervised next-feature objective. RL v2 completed but failed navigation; see the seed correction above. The next bounded pilot compares original starts with a training-only near-to-far curriculum, then evaluates both greedy and sampled actions from original starts. No manual annotation is required.</p><p>'+link('docs/RL_NAVIGATION.html','Bulk RL experiment commands and definitions')+'</p>'
body+='<p>'+link('docs/RL_EXPLORATION.html','Next exploration pilot: commands and interpretation')+'</p>'
out.write_text('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VLA research hub</title><style>body{font:17px system-ui;line-height:1.55;max-width:1450px;margin:40px auto;padding:24px;color:#182333}h1{font-size:38px}h2{margin-top:55px;border-top:2px solid #ddd;padding-top:20px}table{border-collapse:collapse}td,th{padding:10px 22px;border-bottom:1px solid #ddd}img{max-width:100%}figure{margin:0}figcaption{font-weight:bold}.triplet{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.path{font:11px monospace;overflow-wrap:anywhere;background:#eef2f5;padding:8px}nav a{margin-right:12px}@media(max-width:850px){.triplet{grid-template-columns:1fr}}</style>'+body)
print(out)
